### ISSUE TITLE
 controlsd reported an error, but I don't know how to view the error message

### ISSUE THREAD

**Issue by CMLNT** [kommuai/bukapilot#132]
<img width="356" alt="image" src="https://github.com/kommuai/bukapilot/assets/13372840/9fee3a66-5647-4766-b4cb-9a9f1be346a0">
I'm adapting another BYD vehicle and I'm having issues with "controlsd"
but I don't know how to view the error message
Is there any way for me to see the exact error message？
For example this error
 File "/data/openpilot/selfdrive/car/byd/bydcan.py", line 5, in <module>
    SetDistance = car.CarState.CruiseState.SetDistance
AttributeError: '_StructModule' object has no attribute 'SetDistance'

**Comment by zapetaai** [comment]
Hey I believe you are not using bukapilot right? If yes, you should remove all the code that are related to distance set.

**Comment by iXcess** [comment]
Hey I believe you are not using bukapilot right? If yes, you should remove all the code that are related to distance set.
