### ISSUE TITLE
dongle_id is None in registration.py

### ISSUE THREAD

**Issue by AlexanderYeohSX** [kommuai/bukapilot#37]
First pass for "id" in data dictionary is always None. 

Does dingdong.cgi use the "id" key during registration?
https://github.com/kommuai/bukapilot/blob/615739a0f82737dbdf9a31180a86f3897665ea4b/selfdrive/athena/registration.py#L71

**Comment by iXcess** [comment]
@benmasato It was me who changed the id to dongle_id, because it was "str_id" before this and it was undefined. So is this "id" part really needed? Or else we just use imei and serial enough?

**Comment by benmasato** [comment]
I've checked the script, the current implementation is expecting three fields, and is hashing the `dongle_id` (which is `None`) to calculate it.  Definitely need to rewrite (which would use only imei and serial), I think we should keep this issue open until the backend is updated.
