### ISSUE TITLE
Complete fw sleepmode

### ISSUE THREAD

**Issue by iXcess** [kommuai/bukapilot#80]
Users with worn out battery have reported that they cannot start their vehicle after idling for more than 3 days.

**Comment by iXcess** [comment]
Let users choose between 1 hour to 33 hours. 33 hours seems to be a good time to shutdown to preserve car battery.

**Comment by benmasato** [comment]
Does this involve safetyfw?

**Comment by iXcess** [comment]
Right now we are just shutting down the phone, but seem like there are some shutdown quiescent current still flowing into the phone if the Safety isn't shut down. STM itself isn't drawing much but to completely prevent major discharge on the battery, we preferably enter sleep mode completely

**Comment by iXcess** [comment]
Power saver state transition.
1. Wait for shutdown timer (3 hours).
2. Shutdown timer hits, send sleep command to safetyfw and get ack from safetyfw through usb_power_mode_pkt, set it to client mode.
3. Vision shutdown.
4. Safetyfw cuts power to vision and enter sleep mode.
5. On ignition interrupt, exit power saver.

**Comment by iXcess** [comment]
Just for archiving purposes. Apparently the culprit is the charging current into the phone eventhough the phone is in shutdown mode.

| State 	| Vision State            	| KommuSafety State 	| Power Draw 	|
|-------	|-------------------------	|-------------------	|------------	|
| 1     	| Shutdown & Charging     	| On                	| 3W         	|
| 2     	| On & Charging           	| On                	| 3.1W       	|
| 3     	| Shutdown & Non-charging 	| On                	| 0.8W       	|
| 4     	| Shutdown & Non-charging 	| Sleep             	| 0.7W       	|
